
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox WindowBox;

	private global::Gtk.ComboBoxEntry ChannelSelect;

	private global::Gtk.ScrolledWindow ConvoScroll;

	private global::Gtk.TextView ConvoView;

	private global::Gtk.HBox BottomBox;

	private global::Gtk.Entry UsernameEntry;

	private global::Gtk.Entry MessageEntry;

	private global::Gtk.Button SendButton;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("CoU Chat");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(12));
		this.DefaultWidth = 640;
		this.DefaultHeight = 480;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.WindowBox = new global::Gtk.VBox();
		this.WindowBox.Name = "WindowBox";
		this.WindowBox.Spacing = 6;
		// Container child WindowBox.Gtk.Box+BoxChild
		this.ChannelSelect = global::Gtk.ComboBoxEntry.NewText();
		this.ChannelSelect.AppendText(global::Mono.Unix.Catalog.GetString("Global Chat"));
		this.ChannelSelect.Name = "ChannelSelect";
		this.ChannelSelect.Active = 0;
		this.WindowBox.Add(this.ChannelSelect);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.WindowBox[this.ChannelSelect]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child WindowBox.Gtk.Box+BoxChild
		this.ConvoScroll = new global::Gtk.ScrolledWindow();
		this.ConvoScroll.Name = "ConvoScroll";
		this.ConvoScroll.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child ConvoScroll.Gtk.Container+ContainerChild
		this.ConvoView = new global::Gtk.TextView();
		this.ConvoView.CanFocus = true;
		this.ConvoView.Name = "ConvoView";
		this.ConvoView.Editable = false;
		this.ConvoView.CursorVisible = false;
		this.ConvoScroll.Add(this.ConvoView);
		this.WindowBox.Add(this.ConvoScroll);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.WindowBox[this.ConvoScroll]));
		w3.Position = 1;
		// Container child WindowBox.Gtk.Box+BoxChild
		this.BottomBox = new global::Gtk.HBox();
		this.BottomBox.Name = "BottomBox";
		this.BottomBox.Spacing = 6;
		// Container child BottomBox.Gtk.Box+BoxChild
		this.UsernameEntry = new global::Gtk.Entry();
		this.UsernameEntry.CanFocus = true;
		this.UsernameEntry.Name = "UsernameEntry";
		this.UsernameEntry.IsEditable = true;
		this.UsernameEntry.WidthChars = 20;
		this.UsernameEntry.MaxLength = 50;
		this.UsernameEntry.InvisibleChar = '●';
		this.BottomBox.Add(this.UsernameEntry);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.BottomBox[this.UsernameEntry]));
		w4.Position = 0;
		w4.Expand = false;
		// Container child BottomBox.Gtk.Box+BoxChild
		this.MessageEntry = new global::Gtk.Entry();
		this.MessageEntry.Sensitive = false;
		this.MessageEntry.CanFocus = true;
		this.MessageEntry.Name = "MessageEntry";
		this.MessageEntry.IsEditable = true;
		this.MessageEntry.MaxLength = 1000;
		this.MessageEntry.InvisibleChar = '●';
		this.BottomBox.Add(this.MessageEntry);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.BottomBox[this.MessageEntry]));
		w5.Position = 1;
		// Container child BottomBox.Gtk.Box+BoxChild
		this.SendButton = new global::Gtk.Button();
		this.SendButton.CanFocus = true;
		this.SendButton.Name = "SendButton";
		this.SendButton.UseUnderline = true;
		this.SendButton.Label = global::Mono.Unix.Catalog.GetString("Connect");
		this.BottomBox.Add(this.SendButton);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.BottomBox[this.SendButton]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		this.WindowBox.Add(this.BottomBox);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.WindowBox[this.BottomBox]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		this.Add(this.WindowBox);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.MessageEntry.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler(this.OnMessageEntryKeyReleaseEvent);
		this.SendButton.Clicked += new global::System.EventHandler(this.SendClicked);
	}
}
