//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coUchat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("coUchat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to channels.
        /// </summary>
        internal static string ChannelFolder {
            get {
                return ResourceManager.GetString("ChannelFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon CoU_Icon {
            get {
                object obj = ResourceManager.GetObject("CoU_Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8181.
        /// </summary>
        internal static string HttpPort {
            get {
                return ResourceManager.GetString("HttpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://childrenofur.com/profile?username=.
        /// </summary>
        internal static string ProfileUrl {
            get {
                return ResourceManager.GetString("ProfileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to robertmcdermot.com.
        /// </summary>
        internal static string ServerUrlDev {
            get {
                return ResourceManager.GetString("ServerUrlDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to server.childrenofur.com.
        /// </summary>
        internal static string ServerUrlLive {
            get {
                return ResourceManager.GetString("ServerUrlLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localhost.
        /// </summary>
        internal static string ServerUrlLocal {
            get {
                return ResourceManager.GetString("ServerUrlLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.txt.
        /// </summary>
        internal static string UsernameFile {
            get {
                return ResourceManager.GetString("UsernameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8282.
        /// </summary>
        internal static string WsPort {
            get {
                return ResourceManager.GetString("WsPort", resourceCulture);
            }
        }
    }
}
